#define MAX_USER_ID 65535
#define MAX_MOVIE_RATING 2147483647
#define MAX_USER_ID_LENGTH 5
#define MAX_MOVIE_RATING_LENGTH 10

#define MAX_LINE_SIZE 200

#define ADD_USER_LENGTH 7
#define DEL_USER_LENGTH 7
#define ADD_MOVIE_LENGTH 8
#define DEL_MOVIE_LENGTH 8
#define MARATHON_LENGTH 8

#define DEFAULT_FIRST_LAST_CHILD -1